deps: Config flutter_local_notifications
deps: Upgrade compiledSdk to 34

flutter_local_notifications

deps: Enable multiDexEnabled for android

deps: Enable coreLibraryDesugaringEnabled

Crashes app with the following error code:

```zsh
Resolving dependencies...
  _flutterfire_internals 1.3.28 (1.3.29 available)
  cloud_firestore 4.16.0 (4.16.1 available)
  cloud_firestore_platform_interface 6.1.12 (6.1.13 available)
  cloud_firestore_web 3.11.0 (3.11.1 available)
  file_picker 5.5.0 (8.0.0+1 available)
  firebase_auth 4.19.0 (4.19.1 available)
  firebase_auth_platform_interface 7.2.1 (7.2.2 available)
  firebase_auth_web 5.11.0 (5.11.1 available)
  firebase_core 2.28.0 (2.29.0 available)
  firebase_core_web 2.14.0 (2.15.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_plugin_android_lifecycle 2.0.17 (2.0.18 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.14.0 available)
  permission_handler 10.4.5 (11.3.1 available)
  permission_handler_android 10.3.6 (12.0.5 available)
  permission_handler_apple 9.1.4 (9.4.4 available)
  permission_handler_platform_interface 3.12.0 (4.2.1 available)
  permission_handler_windows 0.1.3 (0.2.1 available)
  test_api 0.6.1 (0.7.1 available)
  uuid 4.3.3 (4.4.0 available)
  vm_service 13.0.0 (14.2.0 available)
Got dependencies!
27 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Building with Flutter multidex support enabled.
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:packageDebug'.
> Could not create task ':app:l8DexDesugarLibDebug'.
   > coreLibraryDesugaring configuration contains no dependencies. If you intend to enable core library desugaring, please add dependencies to coreLibraryDesugaring configuration.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

deps: Add coreLibraryDesugaring to deps

Fails compilation with error message:
```zsh
Resolving dependencies...
  _flutterfire_internals 1.3.28 (1.3.29 available)
  cloud_firestore 4.16.0 (4.16.1 available)
  cloud_firestore_platform_interface 6.1.12 (6.1.13 available)
  cloud_firestore_web 3.11.0 (3.11.1 available)
  file_picker 5.5.0 (8.0.0+1 available)
  firebase_auth 4.19.0 (4.19.1 available)
  firebase_auth_platform_interface 7.2.1 (7.2.2 available)
  firebase_auth_web 5.11.0 (5.11.1 available)
  firebase_core 2.28.0 (2.29.0 available)
  firebase_core_web 2.14.0 (2.15.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_plugin_android_lifecycle 2.0.17 (2.0.18 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.14.0 available)
  permission_handler 10.4.5 (11.3.1 available)
  permission_handler_android 10.3.6 (12.0.5 available)
  permission_handler_apple 9.1.4 (9.4.4 available)
  permission_handler_platform_interface 3.12.0 (4.2.1 available)
  permission_handler_windows 0.1.3 (0.2.1 available)
  test_api 0.6.1 (0.7.1 available)
  uuid 4.3.3 (4.4.0 available)
  vm_service 13.0.0 (14.2.0 available)
Got dependencies!
27 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Building with Flutter multidex support enabled.
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

Note: /Users/MBP/.pub-cache/hosted/pub.dev/cloud_firestore-4.16.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
ERROR:D8: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.
ERROR:D8: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.
ERROR:D8: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.
Error: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.
ERROR:D8: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.
ERROR:D8: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.
ERROR:D8: Unsupported desugared library configuration version, please upgrade the D8/R8 compiler.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:l8DexDesugarLibDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.L8DexWorkAction
   > Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

deps: Upgraded build:gradle to 7.3.1

Caused error:

Resolving dependencies...
  _flutterfire_internals 1.3.28 (1.3.29 available)
  cloud_firestore 4.16.0 (4.16.1 available)
  cloud_firestore_platform_interface 6.1.12 (6.1.13 available)
  cloud_firestore_web 3.11.0 (3.11.1 available)
  file_picker 5.5.0 (8.0.0+1 available)
  firebase_auth 4.19.0 (4.19.1 available)
  firebase_auth_platform_interface 7.2.1 (7.2.2 available)
  firebase_auth_web 5.11.0 (5.11.1 available)
  firebase_core 2.28.0 (2.29.0 available)
  firebase_core_web 2.14.0 (2.15.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_plugin_android_lifecycle 2.0.17 (2.0.18 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.14.0 available)
  permission_handler 10.4.5 (11.3.1 available)
  permission_handler_android 10.3.6 (12.0.5 available)
  permission_handler_apple 9.1.4 (9.4.4 available)
  permission_handler_platform_interface 3.12.0 (4.2.1 available)
  permission_handler_windows 0.1.3 (0.2.1 available)
  test_api 0.6.1 (0.7.1 available)
  uuid 4.3.3 (4.4.0 available)
  vm_service 13.0.0 (14.2.0 available)
Got dependencies!
27 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Building with Flutter multidex support enabled.
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Error while evaluating property 'extraGeneratedResDir' of task ':app:mapDebugSourceSetPaths'
   > Failed to calculate the value of task ':app:mapDebugSourceSetPaths' property 'extraGeneratedResDir'.
      > Querying the mapped value of provider(interface java.util.Set) before task ':app:processDebugGoogleServices' has completed is not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

deps: Add fix for enabling desugaring

Error:
Resolving dependencies...
  _flutterfire_internals 1.3.28 (1.3.29 available)
  cloud_firestore 4.16.0 (4.16.1 available)
  cloud_firestore_platform_interface 6.1.12 (6.1.13 available)
  cloud_firestore_web 3.11.0 (3.11.1 available)
  file_picker 5.5.0 (8.0.0+1 available)
  firebase_auth 4.19.0 (4.19.1 available)
  firebase_auth_platform_interface 7.2.1 (7.2.2 available)
  firebase_auth_web 5.11.0 (5.11.1 available)
  firebase_core 2.28.0 (2.29.0 available)
  firebase_core_web 2.14.0 (2.15.0 available)
  flutter_lints 2.0.3 (3.0.2 available)
  flutter_plugin_android_lifecycle 2.0.17 (2.0.18 available)
  js 0.6.7 (0.7.1 available)
  leak_tracker 10.0.0 (10.0.5 available)
  leak_tracker_flutter_testing 2.0.1 (3.0.5 available)
  leak_tracker_testing 2.0.1 (3.0.1 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.8.0 (0.11.1 available)
  meta 1.11.0 (1.14.0 available)
  permission_handler 10.4.5 (11.3.1 available)
  permission_handler_android 10.3.6 (12.0.5 available)
  permission_handler_apple 9.1.4 (9.4.4 available)
  permission_handler_platform_interface 3.12.0 (4.2.1 available)
  permission_handler_windows 0.1.3 (0.2.1 available)
  test_api 0.6.1 (0.7.1 available)
  uuid 4.3.3 (4.4.0 available)
  vm_service 13.0.0 (14.2.0 available)
Got dependencies!
27 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Building with Flutter multidex support enabled.
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Error while evaluating property 'extraGeneratedResDir' of task ':app:mapDebugSourceSetPaths'
   > Failed to calculate the value of task ':app:mapDebugSourceSetPaths' property 'extraGeneratedResDir'.
      > Querying the mapped value of provider(interface java.util.Set) before task ':app:processDebugGoogleServices' has completed is not supported

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

deps: Upgrade google-services to 4.3.14